const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 36,
    employed: true,
    gpa: null,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    employed: false,
    gpa: 7.5,
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 42,
    employed: false,
    gpa: 9.0,
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    age: 30,
    employed: true,
    gpa: 8.5,
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    age: 34,
    employed: true,
    gpa: 8.0,
  },
  {
    id: 6,
    name: "David Wilson",
    email: "david.wilson@example.com",
    age: 26,
    employed: false,
    gpa: 7.0,
  },
  {
    id: 7,
    name: "Emily Thompson",
    email: "emily.thompson@example.com",
    age: 38,
    employed: true,
    gpa: 8.2,
  },
  {
    id: 8,
    name: "Frank Miller",
    email: "frank.miller@example.com",
    age: 29,
    employed: false,
    gpa: 8.8,
  },
  {
    id: 9,
    name: "Grace Wilson",
    email: "grace.wilson@example.com",
    age: 35,
    employed: false,
    gpa: 8.4,
  },
  {
    id: 10,
    name: "John Smith",
    email: "john.smith@example.com",
    age: 36,
    employed: false,
    gpa: 8.9,
  },
];

export { users as default };
